[package]
name = "lib_vssparser"
version = "0.1.0"
authors = ["fulup@iot.bzh"]
edition = "2021"

[dependencies]
nom = { version = "7", features = ["alloc"] }

[lib]
name = "vssparser"
crate-type = ["lib"]
path = "src/vss-lib.rs"
